### ISSUE TITLE
Add a new feature - per permission percentage of drop spawner

### ISSUE THREAD

**Issue by xhelyox** [timbru31/SilkSpawners#340] opened 2021-12-02 21:50 UTC
# Feature Request

## Motivation Behind Feature
]
I think it would be very cool if the plugin have a permission for set the percentage of certain group-player of dropping the spawner
So you could do some p2w things with this feature or something.

## Feature Description
 You'll be able to input a percentage of dropping a spawner in a group or player. If there's not such permission like silkspawners.silkprobability."" so the plugin will use the config percentage.

## Alternatives or Workarounds
There's not

## /version output?

  This server is running Airplane version git-Airplane-106 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 7a9a849 on HEAD)

 1.17.1

## SilkSpawners version

 7.1.0

**Comment by timbru31** [comment] 2021-12-03 08:59
Duplicate of #82

**Closed by timbru31** 2021-12-03 08:59 UTC
