### ISSUE TITLE
Moving spawner in inventory glitch

### ISSUE THREAD

**Issue by Agazed** [timbru31/SilkSpawners#19] opened 2015-07-18 14:24 UTC
Ill let the video explain iteself

https://www.youtube.com/watch?v=_u8KyTFHRHY

**Comment by timbru31** [comment] 2015-07-21 17:50
Duplicate of #17 
This does occur without SilkSpawners, too
MC 1.8.7, no plugins, Spigot 

[19:45:21 INFO]: This server is running CraftBukkit version git-Spigot-c8a0d06-58d972f (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

**Closed by timbru31** 2015-07-21 17:50 UTC

**Comment by timbru31** [comment] 2015-07-21 18:05
I've created a Spigot bug report here:
https://hub.spigotmc.org/jira/browse/SPIGOT-1065
