### ISSUE TITLE
Spawners randomly break overtime

### ISSUE THREAD

**Issue by Callum0508** [timbru31/SilkSpawners#235] opened 2020-05-23 01:35 UTC
#156  What steps will reproduce the problem?
Again, seems like a random occurrence unsure if other people are getting the same issue but overtime the spawners placed will just be blank spawners

## Expected output

I expect the spawner placed to be the actual spawner placed

## What do you see instead?

Blank spawner which doesn't spawn anything

## Log file of the issue/error

None

## /version output?

StellarSpigot 1.8

## SilkSpawners version

SilkSpawners 6.0.1

## Please provide any additional information below.

Overtime on my server spawners randomly stop working and when this happens the spawners placed turn into blank spawners which spawn nothing but spawners placed before this bug occurs work perfectly, this has happened 4 times in the past 2 days

Plugin List:
https://gyazo.com/50b8e6e439fdcef65b90cb2d09dfa7de
https://gyazo.com/facbe8abba7a6c4d2422837f04128cc8

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment] 2020-05-23 07:17
Duplicate of #234, no valid version output. Please try dev build 86.

**Closed by timbru31** 2020-05-23 07:17 UTC
