### ISSUE TITLE
Spawners dupe

### ISSUE THREAD

**Issue by jackofreddo** [timbru31/SilkSpawners#231] opened 2020-05-03 17:27 UTC
## What steps will reproduce the problem?

when you place a spawner for the first time, it doesn't get removed from your inventory so you can place another one, causing you to have 1 extra spawner to what it says on in the inventory.

## Expected output

you should have spawner removed, and only be able  to place same number as number in inventory.

## What do you see instead?

you can place 1 more than the number displayed in the inventory

## Log file of the issue/error

no errors in the logs, logs are all good, happens in game

## /version output?

this server is running paper version git-paper-229 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

## SilkSpawners version

6.0.0

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

i cant upload the video here, i could send it

**Comment by timbru31** [comment] 2020-05-03 18:14
Probably duplicate of #226 - please try https://github.com/timbru31/SilkSpawners/releases/tag/SilkSpawners-6.0.1 (already awaiting review on BukkitDev)

**Comment by jackofreddo** [comment] 2020-05-03 18:27
yeah cool that fixed it, thanks

**Closed** 2020-05-03 18:27 UTC
