### ISSUE TITLE
Explosion-chance separate options

### ISSUE THREAD

**Issue by baticag** [timbru31/SilkSpawners#108] opened 2018-01-02 13:48 UTC
Can you separate config options for creeper-explosion chance and tnt-explosion chance?
Thank you in advance!

**Comment by timbru31** [comment] 2018-01-04 13:00
Hi @baticag, 

thanks for the suggestion, I'll take a look.

**Comment by baticag** [comment] 2018-01-23 00:53
Hey mate,

Any news about this?

**Comment by timbru31** [comment] 2018-01-24 10:11
Thanks for your reminder @baticag - sadly I had no spare time for plugin development in the last few weeks. I'm hopefully able to spend some time this weekend towards SilkSpawners development.

**Comment by timbru31** [comment] 2018-01-30 00:01
This is a dupe of #67 - closing this one.

**Closed by timbru31** 2018-01-30 00:01 UTC
Labels: enhancement
