### ISSUE TITLE
Iron Golem spawners cause massive lag

### ISSUE THREAD

**Issue by trolley1911** [timbru31/SilkSpawners#263] opened 2020-07-29 15:55 UTC
## What steps will reproduce the problem?
Placing an spawner on the ground and changing it to iron golem / giving yourself an iron golem spawner and placing it on the ground

## Expected output
It should spawn golems without affecting game performance

## What do you see instead?
10fps on the first spawner placed and 1fps if I place about 5. Also the entity inside the spawner (little ig) is not there and I will tell you why that matters: In the dev console of the game I see an error being spammed around 20 times a second (ticking tile entity thing?) and it's related to rendering that little entity and not being able to do so. The spawner works as intended but the lag is unbearable. Also the issue is only if I am in presence of the chunk containing the respective spawner, if I go further away everything is fine.

## Log file of the issue/error
This is the error that repeats itself over and over again:
[29Jul2020 15:06:31.270] [Render thread/WARN] [net.minecraft.entity.EntityType/]: Exception loading entity: 
net.minecraft.crash.ReportedException: Loading entity NBT
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1487) ~[?:?]
	at net.minecraft.entity.EntityType.lambda$loadEntityUnchecked$2(EntityType.java:452) ~[?:?]
	at net.minecraft.util.Util.func_215077_a(SourceFile:401) ~[?:?]
	at net.minecraft.entity.EntityType.func_220330_a(EntityType.java:449) ~[?:?]
	at net.minecraft.entity.EntityType.func_220343_b(EntityType.java:507) ~[?:?]
	at net.minecraft.entity.EntityType.func_220335_a(EntityType.java:489) ~[?:?]
	at net.minecraft.world.spawner.AbstractSpawner.func_184994_d(AbstractSpawner.java:252) ~[?:?]
	at net.minecraft.client.renderer.tileentity.MobSpawnerTileEntityRenderer.func_225616_a_(SourceFile:22) ~[?:?]
	at net.minecraft.client.renderer.tileentity.MobSpawnerTileEntityRenderer.func_225616_a_(SourceFile:12) ~[?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101) ~[?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:85) ~[?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118) ~[?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1017) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.1-forge-32.0.97.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.97.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
Caused by: java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	at net.minecraft.entity.passive.IronGolemEntity.func_70037_a(IronGolemEntity.java:153) ~[?:?]
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1472) ~[?:?]
	... 28 more

## /version output?
This server is running Paper version git-Paper-113 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

## SilkSpawners version
v6.3.1 (for 1.16, as of 29.07.2020)

## Please provide any additional information below.
I tried reproducing the issue with 3 other friends. Same minecraft launcher version, same windows, same java. We all have the same error spamming the console and massive lag but one of us has lag only ocasionally. Maybe because he has an ati and we have nvidia. Tried it with intel hd too, same issue. I looked for some tile entity mod to not render that spawner or something but only found an outdated mod and I don't know how to code. I really wish I can find a solution for this. I originally discovered this issue on a server then made one of my own with only this plugin installed. Without the plugin giving myself an iron golem spawner with the give command actually gives me a pig one that for a second has no entity inside then resets to being a pig one and when I put the plugin the spawner block stays without an entity always (it doesn't happen to other mob spawners). THANK YOU!

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment] 2020-07-29 16:07
Can't reproduce. I see you run a modded client and Forge - please try without it. Besides that, please update your Paper, your behind. Where did you obtain the spawners from? /ss give?

**Comment by trolley1911** [comment] 2020-07-29 16:17
I'll try vanilla right now, bear with me a minute. Yes I tried with ss give, then by placing a normal spawner block and changing it with ss change.

**Comment by trolley1911** [comment] 2020-07-29 16:23
/version - This server is running Paper version git-Paper-127 (MC: 1.16.1) (Implementing API version 1.16.1-R.01-SNAPSHOT)

Dev console log with everything updated on my test server:
[17:22:37] [Render thread/WARN]: Exception loading entity: 
> s: Loading entity NBT
> 	at aom.f(SourceFile:1645) ~[1.16.1.jar:?]
> 	at aoq.a(SourceFile:468) ~[1.16.1.jar:?]
> 	at v.a(SourceFile:401) ~[1.16.1.jar:?]
> 	at aoq.a(SourceFile:467) ~[1.16.1.jar:?]
> 	at aoq.b(SourceFile:530) ~[1.16.1.jar:?]
> 	at aoq.a(SourceFile:511) ~[1.16.1.jar:?]
> 	at bpd.d(SourceFile:256) ~[1.16.1.jar:?]
> 	at eei.a(SourceFile:22) ~[1.16.1.jar:?]
> 	at eei.a(SourceFile:12) ~[1.16.1.jar:?]
> 	at edw.a(SourceFile:107) ~[1.16.1.jar:?]
> 	at edw.b(SourceFile:96) ~[1.16.1.jar:?]
> 	at edw.a(SourceFile:128) [1.16.1.jar:?]
> 	at edw.a(SourceFile:96) [1.16.1.jar:?]
> 	at ebx.a(SourceFile:1240) [1.16.1.jar:?]
> 	at ebs.a(SourceFile:717) [1.16.1.jar:?]
> 	at ebs.a(SourceFile:540) [1.16.1.jar:?]
> 	at dlx.e(SourceFile:1021) [1.16.1.jar:?]
> 	at dlx.e(SourceFile:654) [1.16.1.jar:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:215) [1.16.1.jar:?]
> Caused by: java.lang.ClassCastException: dym cannot be cast to zd
> 	at ayt.a(SourceFile:170) ~[1.16.1.jar:?]
> 	at aom.f(SourceFile:1636) ~[1.16.1.jar:?]
> 	... 18 more

Thank you for replying so fast, I really appreciate it!

**Comment by trolley1911** [comment] 2020-07-29 16:27
Also if you know anything or have any idea about how I can at least not render any spawner block (I guess that will fix it) point me in the right direction. I know you don't have to, at all but I'm out of options and I can't learn to code to fix this specific issue (or rendering one) as coding is a long way with a lot of variables until I could be able to properly understand what I have to do.

**Comment by timbru31** [comment] 2020-08-02 19:13
The stack traces you've posted all are native Minecraft ones, nothing related to SilkSpawners. It seems you are affected by this Minecraft bug: https://bugs.mojang.com/browse/MC-189565 - I'm closing this issue since this is out of scope of my plugin.

**Closed by timbru31** 2020-08-02 19:13 UTC
