### ISSUE TITLE
Could not pass event BlockBreakEvent to SilkSpawners v6.0.0

### ISSUE THREAD

**Issue by DevelopmentHigh** [timbru31/SilkSpawners#227] opened 2020-05-01 20:27 UTC
## What steps will reproduce the problem?

When place spawn it turns on pig if player is not op, if player is op giving them error

## Log file of the issue/error

`Could not pass event BlockBreakEvent to SilkSpawners v6.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:121) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:626) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
	at de.dustplanet.util.SilkUtil.canBuildHere(SilkUtil.java:856) ~[?:?]
	at de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener.onBlockBreak(SilkSpawnersBlockListener.java:56) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor254.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 18 more`

## /version output?

Paperspigot 1.8.8

## SilkSpawners version

6.0.0

**Comment by timbru31** [comment] 2020-05-01 21:54
Duplicate of #225

**Comment by timbru31** [comment] 2020-05-01 21:54
Use https://ci.dustplanet.de/job/SilkSpawners/54/ :)

**Closed by timbru31** 2020-05-01 21:54 UTC

**Comment by DevelopmentHigh** [comment] 2020-05-02 00:37
> Use https://ci.dustplanet.de/job/SilkSpawners/54/ :)

Okay i will try :)

**Comment by timbru31** [comment] 2020-05-02 12:17
Great. An official update (6.0.1) is awaiting review and approval on BukkitDev, too.
