### ISSUE TITLE
SilkSpawners error with WorldGuard

### ISSUE THREAD

**Issue by Permanently** [timbru31/SilkSpawners#228] opened 2020-05-02 15:25 UTC
## What steps will reproduce the problem?
Instance 1:
1. Run a Spigot 1.12.2-R0.1 server, install SilkSpawners v6.0.0, [WorldGuard v6.2.2](https://dev.bukkit.org/projects/worldguard/files/2610618), [WorldGuardEliminate v1.5](https://dev.bukkit.org/projects/wg-eliminate/files/2441819) and [WorldGuardExtraFlags v4.1.2](https://www.spigotmc.org/resources/4823/update?update=260887).
2. Give yourself a custom spawner (in this case, a cow spawner) and place it down.
3. Assess.

Instance 2:
1. Run a Spigot 1.12.2-R0.1 server, install SilkSpawners v6.0.0, [WorldGuard v6.2.2](https://dev.bukkit.org/projects/worldguard/files/2610618), [WorldGuardEliminate v1.5](https://dev.bukkit.org/projects/wg-eliminate/files/2441819) and [WorldGuardExtraFlags v4.1.2](https://www.spigotmc.org/resources/4823/update?update=260887).
2. Try to run a command to change a spawner. In my case, this was `/ss change cow`.
3. Assess.

## Expected output
The spawner would be placed as a cow.

The pig spawner would change to a cow spawner.

## What do you see instead?
A pig spawner.

Still a pig spawner.

## Log file of the issue/error
Instance 1:
```
02.05 16:05:54 [Server] ERROR Could not pass event BlockPlaceEvent to SilkSpawners v6.0.0
02.05 16:05:54 [Server] INFO org.bukkit.event.EventException: null
02.05 16:05:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:150) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:953) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
02.05 16:05:54 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
02.05 16:05:54 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
02.05 16:05:54 [Server] INFO at de.dustplanet.util.SilkUtil.canBuildHere(SilkUtil.java:856) ~[?:?]
02.05 16:05:54 [Server] INFO at de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener.onBlockPlace(SilkSpawnersBlockListener.java:193) ~[?:?]
02.05 16:05:54 [Server] INFO at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source) ~[?:?]
02.05 16:05:54 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
02.05 16:05:54 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
02.05 16:05:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO ... 18 more
02.05 16:05:54 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
02.05 16:05:54 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
02.05 16:05:54 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
02.05 16:05:54 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
02.05 16:05:54 [Server] INFO at de.dustplanet.util.SilkUtil.canBuildHere(SilkUtil.java:856) ~[?:?]
02.05 16:05:54 [Server] INFO at de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener.onBlockPlace(SilkSpawnersBlockListener.java:193) ~[?:?]
02.05 16:05:54 [Server] INFO at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source) ~[?:?]
02.05 16:05:54 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
02.05 16:05:54 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
02.05 16:05:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:05:54 [Server] INFO ... 18 more
```

Instance 2:
```
02.05 16:51:42 [Server] INFO Permanently issued server command: /ss change cow
02.05 16:51:42 [Server] ERROR null
02.05 16:51:42 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ss' in plugin SilkSpawners v6.0.0
02.05 16:51:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
02.05 16:51:42 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
02.05 16:51:42 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
02.05 16:51:42 [Server] INFO at de.dustplanet.util.SilkUtil.canBuildHere(SilkUtil.java:856) ~[?:?]
02.05 16:51:42 [Server] INFO at de.dustplanet.util.SilkUtil.setSpawnerType(SilkUtil.java:528) ~[?:?]
02.05 16:51:42 [Server] INFO at de.dustplanet.silkspawners.commands.SpawnerCommand.handleBlockChange(SpawnerCommand.java:284) ~[?:?]
02.05 16:51:42 [Server] INFO at de.dustplanet.silkspawners.commands.SpawnerCommand.handleChange(SpawnerCommand.java:240) ~[?:?]
02.05 16:51:42 [Server] INFO at de.dustplanet.silkspawners.commands.SpawnerCommand.onCommand(SpawnerCommand.java:59) ~[?:?]
02.05 16:51:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
02.05 16:51:42 [Server] INFO ... 15 more
```

## /version output?
`This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

## SilkSpawners version
v6.0.0

## Please provide any additional information below.
From looking at the error, it looks like there's some kind of issue with WorldGuard. I don't think it's WorldGuardEliminate or WorldGuardExtraFlags, but I've included them as they could potentially be doing something. I dunno, I'm not that experienced with Java.

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment] 2020-05-02 15:46
Duplicate of #225 - use https://github.com/timbru31/SilkSpawners/releases/tag/SilkSpawners-6.0.1 (already awaiting review on BukkitDev)

**Closed by timbru31** 2020-05-02 15:46 UTC
