### ISSUE TITLE
No support for my version

### ISSUE THREAD

**Issue by TuXFX** [timbru31/SilkSpawners#161] opened 2018-09-12 13:10 UTC
## What steps will reproduce the problem?

I'm not entirely sure, it was working fine but recently I kept getting the same error on server startup.

## Expected output

No errors and it all run correctly.

## What do you see instead?

https://pastebin.com/q79U7JYV

## Log file of the issue/error

https://pastebin.com/q79U7JYV

## /version output?

I've switched from the newest Silkspawners, to the first known 1.8, to some ones in between. They all seem to be giving me the same issue. I am running a 1.8.9 spigot server.

## SilkSpawners version

The two main ones ive used was 5.02v, and 3.61v.

## Please provide any additional information below.

Keep up the great work.

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment] 2018-11-18 19:52
Please add a valid /version output, otherwise I can't help.

**Comment by CryLegende** [comment] 2018-12-21 09:59
Same issue

Server: git-Paper-1594 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
SilkSpawner: 5.0.2 (Latest version on Bukkit/Spigot)
Full error: https://pastebin.com/raw/PHZFfx8P

**Comment by timbru31** [comment] 2019-01-03 20:01
@CryLegende - does SilkSpawners work **without** MergedSpawners and ShopGUI+? Additionally, your Java version (java -version) would be interesting.

**Comment by CryLegende** [comment] 2019-01-03 20:08
Hello ^^
Java 8
SilkSpawners work with and without MergedSpawners and ShopGUI+ but when one of this plugin is installed, i have an error from SilkSpawner.
Logs of SilkSpawner withtout MergedSpawners and ShopGUI+: https://pastebin.com/raw/Sr6JYpau

**Comment by timbru31** [comment] 2019-01-03 20:11
Are both MergedSpawners and ShopGUI+ the latest version? Can you provide a full server startup log please?  
Besides that, Java 8 is not precise enough. Open a terminal and type `java -version` to get the full Java version

**Comment by CryLegende** [comment] 2019-01-03 20:15
`
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
`
Latest version of MergedSpawners and version 1.8.5 of ShopGui+ (1.8.5 is the latest version with the 1.12.2 ID for the spawners but the problem is the same with the latest version)
Check your SpigotMC pm for the jar, just 2 min

**Comment by timbru31** [comment] 2019-01-03 21:34
Please give https://ci.dustplanet.de/job/SilkSpawners/494 a try - to see if the plugins are at least loading correctly.

**Comment by CryLegende** [comment] 2019-01-03 21:43
I test it in an hour

**Comment by CryLegende** [comment] 2019-01-04 00:45
Full logs: https://pastebin.com/raw/kfENsGWb (SilkSpawner Build 494)

**Comment by timbru31** [comment] 2019-01-04 12:46
Please try https://ci.dustplanet.de/job/SilkSpawners/501

**Comment by CryLegende** [comment] 2019-01-05 01:50
Full logs: https://pastebin.com/raw/hp0h2QHT (SilkSpawner Build 501)

**Comment by CryLegende** [comment] 2019-01-06 17:04
I use Paper#1595 (latest build)
Names of the plugins:
ShopGUIPlus-1.18.5-SNAPSHOT.jar
MergedSpawner (59).jar

**Comment by CryLegende** [comment] 2019-01-06 17:33
SilkSpawners (14).jar
Paper.yml: https://pastebin.com/raw/5SLH8h0a

**Comment by timbru31** [comment] 2019-01-06 17:50
Can you try to rename all .jar files and remove and numbers in ()? e.g. `SilkSpawners (14).jar` to `SilkSpawners.jar`.

**Comment by CryLegende** [comment] 2019-01-06 19:52
https://pastebin.com/raw/FCf2dxGP
SilkSpawner.jar
MergedSpawner.jar
ShopGuiPlus.jar

**Comment by CryLegende** [comment] 2019-01-06 20:02
I have add that in plugin.yml of MergedSpawner and that work, MergedSpawner load before SilkSpawner
`depend: [SilkSpawners]`

**Closed** 2020-05-09 16:19 UTC
Labels: invalid, waiting-for-feedback
