### ISSUE TITLE
Plugin completely broke on me.

### ISSUE THREAD

**Issue by v1t0man36658** [timbru31/SilkSpawners#113] opened 2018-01-29 23:41 UTC
## What steps will reproduce the problem?
Just the entire plugin is not working. So using any of the commands result in the problem.
## Expected output
Supposed to have the mobnames listed correctly as cow, chicken, creeper etc and they're supposed to spawn their mobs and be able to be picked up.
## What do you see instead?
They have been renamed to 'mycow', 'mychicken', etc. They have 'my' in front of them.
## Log file of the issue/error
Just the screenshots of what I see in-game, but the console does not produce any error or message regarding SS.

http://prntscr.com/i7eynl

Any help is appreciated. Thanks.
## SilkSpawners version
5.0.0

## Please provide any additional information below.
Check the screenshot link above. 
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by v1t0man36658** [comment] 2018-01-29 23:42
Plugin was working perfectly since I've downloaded it, no new plugins were installed, no configuration files have been touched. It simply broke yesterday.

**Comment by timbru31** [comment] 2018-01-29 23:58
Another plugin overwrote the default mobs. SilkSpawners only loads what's registered. 100% caused by another plugin.

**Comment by v1t0man36658** [comment] 2018-01-30 00:12
Mind throwing some insight on which one? Here are my current plugin lists.
http://prntscr.com/i7fcam

**Comment by timbru31** [comment] 2018-01-30 00:44
Try to remove
* MyPet
* HolographicDisplays
* MobHunting

This is just a best guess, but at least MyPet and HolographicDisplays caused issues in the past.

**Comment by timbru31** [comment] 2018-02-03 17:44
@v1t0man36658 any news on this issue? Did disabling any of those plugins above helped?

**Comment by v1t0man36658** [comment] 2018-02-04 05:40
I apologize for the response delay, indeed you were correct. After removing MyPets from my plugin list, SilkSpawner started working as it should be. 
Now I'm trying to check why MyPets does that since I've had both plugins work together in harmony for the past month and a half. So not sure why it started now.
Yes, your suggestion of removing MyPet worked. So cheers!
Best,Vito


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Tim Brust <notifications@github.com> Date: 2/3/18  12:44 PM  (GMT-05:00) To: timbru31/SilkSpawners <SilkSpawners@noreply.github.com> Cc: v1t0man36658 <theasvisnetwork@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [timbru31/SilkSpawners] Plugin completely broke on me. (#113) 
@v1t0man36658 any news on this issue? Did disabling any of those plugins above helped?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/timbru31/SilkSpawners","title":"timbru31/SilkSpawners","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/timbru31/SilkSpawners"}},"updates":{"snippets":[{"icon":"PERSON","message":"@timbru31 in #113: @v1t0man36658 any news on this issue? Did disabling any of those plugins above helped?"}],"action":{"name":"View Issue","url":"https://github.com/timbru31/SilkSpawners/issues/113#issuecomment-362838926"}}}

**Comment by timbru31** [comment] 2018-02-04 23:09
Have you recently updated MyPets? The update history said it was updated ~2 weeks ago (https://www.spigotmc.org/resources/mypet.12725/updates)

**Comment by timbru31** [comment] 2018-02-12 15:51
Closing, since I can't do anything from my end and the culprit was identified.

**Closed by timbru31** 2018-02-12 15:51 UTC
Labels: plugin-conflict, waiting-for-feedback

**Comment by v1t0man36658** [comment] 2018-02-19 21:47
Hi,

Okay so we stopped using MyPets and the issue I thought was fixed, it NOW identifies the mob name correctly, so I can now do /ss give USERNAME cow 1 and it'll give me a spawner called cow instead of typing ss give Username mycow 1. 

Issue lies that they're pig spawners, as if all their data was cleaned off. Any other recommendations from the plugins I'm running right now (same as in the screenshot, but without MyPets)
