### ISSUE TITLE
NPE preventing from using the API

### ISSUE THREAD

**Issue by Fleodas** [timbru31/SilkSpawners#90] opened 2017-07-24 19:16 UTC
## What steps will reproduce the problem?

Use this code in a plugin:
SilkUtil su = SilkUtil.hookIntoSilkSpanwers();

## Expected output
No error.

## What do you see instead?
Error in console preventing my plugin from loading.

## Log file of the issue/error
https://pastebin.com/E0spC7wa

## /version output?
CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

## SilkSpawners version
4.0.0
Problem happens on 3.7.4 too.

**Comment by timbru31** [comment] 2017-07-24 19:18
Can you please post some code snippets of your plugin, where you call the SilkSpawners API? I'm missing a reproducible example.

Dupe of #87

**Comment by Fleodas** [comment] 2017-07-24 19:22
Code used: https://gist.github.com/Fleodas/6081e0b30d299db3a6546394156e7d3a

**Comment by timbru31** [comment] 2017-07-24 20:06
Thanks!
Make sure to add `depend: [SilkSpawners]` to your `plugin.yml` and move the initialization of SilkUtil into your `onEnable()` method - otherwise SilkSpawners is not yet correctly initialized.
```java
private SilkUtil su;

@Override
public void onEnable() {
  // do your stuff
  su = SilkUtil.hookIntoSilkSpanwers();
  ...
}
```

I'll add a warning nevertheless.

**Closed by timbru31** 2017-07-24 20:06 UTC
Labels: api, bug, question, waiting-for-feedback

**Comment by Fleodas** [comment] 2017-07-24 20:17
Thanks!

You should document the API, I only found this page with broken javadocs: https://dev.bukkit.org/projects/silkspawners/pages/api

**Comment by timbru31** [comment] 2017-07-24 20:19
Will do 👍
