### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by MasterGabeMOD** [timbru31/SilkSpawners#199] opened 2019-04-29 04:41 UTC
Video of how to do the dupe glitch https://streamable.com/rzsfl

Only seems to be an issue with 1.13 sea creatures or any other new 1.13 mobs.

[Server] INFO This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

SilkSpawners v6.0.0-SNAPSHOT-b503

Plugins (75): AdvancedGambler, AdvancedPortals, AnimatedNames*, ArtMap, AuctionHouse, BeastTokens, BottledExp, BuycraftX*, CartographerLagFix*, ChatControl, Citizens, CommandNPC*, CoreProtect, CrazyCrates, CustomFishing*, CustomTrash*, DeluxeChat, DeluxeMenus*, Edit_Mobs, EditableSign, Elevator*, EntityControl, EpicRename, EpicWorldGenerator, Essentials, EssentialsChat, EssentialsExtras*, EssentialsSpawn, EZBlocks*, FBasics*, FeatherBoard*, GriefPrevention, GuiRedeemMCMMO*, HeadBuyerSP*, HeadDatabase*, HideAchievements*, HideStream*, HolographicDisplays, KickFromClaim*, LagAssist, LibsDisguises, LuckPerms, MarriageMaster, mcMMO, MergedSpawner, MFHoppers, MineResetLite, Multiverse-Core, MVdWPlaceholderAPI*, MyPrefix, OldCombatMechanics, PandaWire, PlaceholderAPI, PlugMan*, PremiumVanish, ProtocolLib*, ProtocolSupport, Quests*, RepairGui*, Sellwands*, ShopGUIPlus, SilkSpawners, SimpleBroadcast*, Spartan, Tab*, TaxSP*, TextCosmetics*, TitleManager*, TradeMe, UltimateTimber, Vault*, VeinMiner, WorldBorder, WorldEdit, WorldGuard

**Comment by Acenox** [comment] 2019-05-04 18:04
I have the same problem :/

**Comment by timbru31** [comment] 2019-05-04 18:06
You have to realize that you are using development builds which might be unstable, not working, or bugged.
1.13+ support ist still unfinished.

**Comment by Acenox** [comment] 2019-05-04 18:28
> You have to realize that you are using development builds which might be unstable, not working, or bugged. 1.13+ support ist still unfinished.
> […](#)
> Sent from my iPhone
> On 4. May 2019, at 8:04 PM, Acenox ***@***.***> wrote: I have the same problem :/ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I am experiencing this problem in spigot 1.8.8 with version 5.0.2

Record: https://www.youtube.com/watch?v=Ebir8HYvpbc&feature=youtu.be and https://www.youtube.com/watch?v=MApZ5p64_2U&feature=youtu.be

Best regards,

**Comment by Acenox** [comment] 2019-05-05 00:04
Update: I just inquired, the problem does not seem to come from SilkSpawner but from MergedSpawner, I just informed the developer.

**Comment by Acenox** [comment] 2019-05-05 11:07
Update : The problem is solved by MergedSpawner, I simply invite you to update MergedSpawner @MasterGabeMOD 

Best regards,

**Comment by timbru31** [comment] 2019-05-05 13:49
Thanks a lot for shining some light into this issue @Acenox - I'm closing this issue.

**Closed by timbru31** 2019-05-05 13:49 UTC
