### ISSUE TITLE
[!] Mining percentage by Permission

### ISSUE THREAD

**Issue by smscentras** [timbru31/SilkSpawners#518] opened 2024-04-07 23:03 UTC
# Feature Request
Mining percentage by permission, in example who have permission silkspawners.silkdrop.20 have 20% to obtain spawner, other players who have silkspawners.silkdrop.5 have obtain chance to obtain spawner - 5%.

## Motivation Behind Feature
Why need? - We have VIP players...

## /version output?

This server is running Paper version git-Paper-477 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 1207162)
You are running the latest version
Previous version: git-Paper-467 (MC: 1.20.4)

## SilkSpawners version

SilkSpawners (Versions 1.8.8 - 1.20.4) 2.2.1

## Please provide any additional information below.
Thank you

**Comment by timbru31** [comment] 2024-04-08 08:30
Duplicate of #82

**Closed by timbru31** 2024-04-08 08:30 UTC
