### ISSUE TITLE
SilkSpawner failing to initialise itself for its NMSProvider.

### ISSUE THREAD

**Issue by CryLegende** [timbru31/SilkSpawners#186] opened 2019-01-02 15:13 UTC
Hello, I have several errors from SilkSpawner when I launch my server.
For ShopGui +, this prevents it from launching when there are spawners in the shop.
For MergedSpawner, This removes all spawners placed on the ground (or makes them empty like this screen: https://i.goopics.net/7Ydxm.png) after the chunk unload and then reload

Spigot: git-Paper-1594 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
SilkSpawner: 5.0.2 (latest) 

The error: https://pastebin.com/raw/a62ZW9ZL (VKLib is MergedSpawner)
That do se same with ShopGui+ (https://pastebin.com/raw/PG4PKMKd)

**Comment by timbru31** [comment] 2019-01-02 16:48
Probably a dupe of #180

**Closed by timbru31** 2019-01-02 16:48 UTC
Labels: api, invalid

**Comment by timbru31** [comment] 2019-01-03 20:05
That's because I cannot reproduce this issue and both conflicting plugins are premium
