### ISSUE TITLE
Untextured spawners

### ISSUE THREAD

**Issue by Gelvinlol** [timbru31/SilkSpawners#121] opened 2018-03-03 11:36 UTC
## What steps will reproduce the problem?
I just installed it.
## Expected output
See Spawners when getting them
## What do you see instead?
This: https://prnt.sc/im8s2d
## Log file of the issue/error
It doesn't have 
## /version output?
Paperspigot 1.7-1.8

## SilkSpawners version
SilkSpawners v3.6 --1.5 up to 1.8--

## Please provide any additional information below.
My plugins: https://prnt.sc/im8soj
## Checklist
-I have not use any texturepack(Extra)
- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by Gelvinlol** [comment] 2018-03-03 11:37
Idk that is going on

**Comment by timbru31** [comment] 2018-08-07 16:25
Closing since no valid version output and broken textures are often caused by protocol hacks and are a client issue.

**Closed by timbru31** 2018-08-07 16:25 UTC
